export const AWS_ACCESS_KEY_ID="xfJm1oGpEdvNHVx0pNXr"
export const AWS_SECRET_ACCESS_KEY="unEcVjXtmSpLUwDCobG5zKV1vLD4d6lmbUK7i8t3"
export const AWS_REGION="us-east-1"
export const AWS_ENDPOINT_URL="https://inet-s3-object-gw-c.inet.co.th"
export const S3_BUCKET_NAME="test-zte"

export const AWS_ACCESS_KEY_ID2="HKGGpivlBJpTiE5EQpnj"
export const AWS_SECRET_ACCESS_KEY2="GszVjnWitTlD3hnpfwMBSRsr7cdVZasRjvsb4TZ2"
export const AWS_REGION2="us-east-1"
export const AWS_ENDPOINT_URL2="inet-s3-object-gw-b.inet.co.th"
export const S3_BUCKET_NAME2="loadtest-lenovo-object-b"