// export const AWS_ACCESS_KEY_ID="xfJm1oGpEdvNHVx0pNXr"
// export const AWS_SECRET_ACCESS_KEY="unEcVjXtmSpLUwDCobG5zKV1vLD4d6lmbUK7i8t3"
// export const AWS_REGION="us-east-1"
// export const AWS_ENDPOINT_URL="https://inet-s3-object-gw-c.inet.co.th"
// export const S3_BUCKET_NAME="test-zte"

// export const AWS_ACCESS_KEY_ID="HKGGpivlBJpTiE5EQpnj"
// export const AWS_SECRET_ACCESS_KEY="GszVjnWitTlD3hnpfwMBSRsr7cdVZasRjvsb4TZ2"
// export const AWS_REGION="us-east-1"
// export const AWS_ENDPOINT_URL="inet-s3-object-gw-b.inet.co.th"
// export const S3_BUCKET_NAME="loadtest-lenovo-object-b"

// export const AWS_ACCESS_KEY_ID="qa9azWui9Y2bSBDevu0p"
// export const AWS_SECRET_ACCESS_KEY="rzrvRW6w9qSJcKGIzQrmLK4EhtHjFQypeHefticX"
// export const AWS_REGION="us-east-1"
// export const AWS_ENDPOINT_URL="inet-s3-object-gw-b.inet.co.th"
// export const S3_BUCKET_NAME="loadtest-object-b"

// export const AWS_ACCESS_KEY_ID="MptWZQ4R07e3iLKsoiJz"
// export const AWS_SECRET_ACCESS_KEY="vDWfXUCTyvrhmj36Mz6Saxvxm9xFL9rIOfaXF23N"
// export const AWS_REGION="us-east-1"
// export const AWS_ENDPOINT_URL="https://inet-s3-object-gw-c.inet.co.th"
// export const S3_BUCKET_NAME="loadtest-object-c"

// export const AWS_ACCESS_KEY_ID="vtjtCcq4EkBinSBmpIfR"
// export const AWS_SECRET_ACCESS_KEY="bEPbAldZABfe5r19UrdLJJePnihU49cucGHfzX2I"
// export const AWS_REGION="us-east-1"
// export const AWS_ENDPOINT_URL="https://inet-s3-object-gw-c.inet.co.th"
// export const S3_BUCKET_NAME="loadtest-zte-object-c"
// export const username = "loadtest"
// export const password = "gmlz,sojvp86["
// export const url  = "https://inet-s3-object-c.inet.co.th"

export const AWS_ACCESS_KEY_ID="u1qD4PAGNCxMcxv37AhT"
export const AWS_SECRET_ACCESS_KEY="cvX3mH6tHCa0BWizyhSE5Q0B5qPsaGaGByvBOkUv"
export const AWS_REGION="us-east-1"
export const AWS_ENDPOINT_URL="192.168.90.32:9000"
export const S3_BUCKET_NAME="loadtest"
export const username = "Loadtest"
export const password = "v'gmlf"
export const url  = "https://192.168.90.32"
